### ISSUE TITLE
Improve current comparison implementation.

### ISSUE THREAD

**Issue by bouzlibop** [TheMindhouse/memospeak#7]
What is returned by jsdiff is hard to use when it comes to marking something as wrong detection.
Furthermore we need to transform input text a bit to handle some special cases listed below.

Test cases:
- [x] When word was only added (nothing removed):
  `Ada ma kota` -> `Ada ma ma kota`
- [x] When word was only removed (nothing added):
  `Ada ma kota` -> `Ada kota`
- [x] When word was replaced by some other word/words:
  `Ada ma kota chyba` -> `Ada ma zapomniałem co kota chyba`
- [x] Special characters (`.`, `-`, `?`, etc.):
  `Ada ma kota?` -> `Ada ma kota`
- [x] Multiple white spaces:
  `Ada ma.........................kota` -> `Ada ma kota`
- [x] Case sensitivity:
  `Ada ma kota` -> `ada ma kota`
- [x] Repeat sentence:
  `Love me like you do la la love me like you do` -> `love me like you do la la love me like you do`

**Comment by krisu-pl** [comment]
Fixed by changing the diff algorithm and creating its clean version
